[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "chmod +x postinstall.sh",
  "./postinstall.sh"
]

[start]
cmd = "python parsers/4399-4400/run.py"
